### ISSUE TITLE
B2 iOS: Mac OS 8.x scroll bar bug

### ISSUE THREAD

**Issue by rakslice** [rakslice/macemu#16]
It's our old friend the scroll bar bug. (B2, Mac OS 8.x only)

The 'thumb' of the scroll bar always draws at the top. The scroll bar works okay, you can interact with it properly with buttons or clicks on the bar or drags as you would a scroll bar at the top, and the window content scrolls, but the thumb itself doesn't move move.

I note that:
68040  -> bug
68030 w/o FPU -> no bug
68030 w/ FPU -> this one crashes at boot so I don't know whether the scroll bar works or not :D

Other platforms seem to be free of this bug now, but judging by the discussion on emaculation in 2018 they still had it then; by that and the above, was it the change from fpu_uae to fpu_ieee that fixed it?

Is that viable at all on iOS? If it is, is it too slow (for instance are there games that use a lot of FPU that are okay with fpu_uae but not fast enough with fpu_ieee)?

**Comment by rakslice** [comment]
Or maybe this is affected in some other way related to '030 vs '040 cases

**Comment by rakslice** [comment]
Yeah, ancient mailing list post from @gbeauchesne suggests that scrollbar issues are in the neighbourhood of FPU precision https://sourceforge.net/p/basilisk/mailman/message/2164083/

**Comment by kanjitalk755** [comment]
Tested on macOS version, using fpu_ieee instead of fpu_uae solves this problem.
