### ISSUE TITLE
MinGW-version launch error

### ISSUE THREAD

**Issue by emendelson** [rakslice/macemu#17]
I built the MinGW version following the instructions on that branch; unfortunately, when I launch it I get this error:

Invalid struct my_stat -- edit posix_emu.h

Is there something I need to change in prefs or can this be fixed in the code?

**Comment by rakslice** [comment]
By coincidence I noticed this just after replying to the emaculation forum thread :D
https://www.emaculation.com/forum/viewtopic.php?f=20&t=10529&p=65351#p65350

**Comment by rakslice** [comment]
Based on the response in the thread https://www.emaculation.com/forum/viewtopic.php?f=20&t=10529&p=65351#p65356 the padding change in `struct my_stat` doesn't work in MSYS (1.x) mingw32. 

I'll try to set up a mingw32 environment based on the notes at https://www.emaculation.com/forum/viewtopic.php?f=6&t=10019 and find a way to have a `struct my_stat` that works both there and in MSYS2.

**Comment by rakslice** [comment]
Should be fixed in ff4456479f84b90700673609a80dd9d3e8a4dd43.

The test in `posix_emu.h` was checking the size of `struct stat`, but that's not the right struct for `_tstat()`, the function `posix_emu` actually uses; it is `_stat`. In MSYS2 `_stat` is not the default `stat`.

**Comment by rakslice** [comment]
So in other words, `_tstat` itself did not need the extra padding, only the bad test in `posix_emu.h`.

**Comment by rakslice** [comment]
I assume this is fixed; feel free to reopen if you're still having the problem.

**Comment by emendelson** [comment]
Yes, fixed, thank you!
