### ISSUE TITLE
OS X: Can't use an actual CD directly

### ISSUE THREAD

**Issue by rakslice** [rakslice/macemu#19]
In OS X, B2/SS can't use a disc directly in the optical drive. I tried explicitly adding its /dev/disk* device to the volumes list but this did not make any difference. 

To verify there wasn't an issue with the disk contents, I used OS X's Disk Utility to take an image of the CD (i.e. in DMG format), then opened the image in OS X and unmounted (but not ejected) it in Disk Utility, and then added the /dev/disk* device for the mounted disk image to the volumes list in the emulator. This read from the image without issue, and even booted from a bootable one.

**Comment by kanjitalk755** [comment]
Because the owner/group is different.

an actual CD:
br--r----- root operator /dev/disk?s1

an image CD:
br--r----- you  staff    /dev/disk?s1

You can mount an actual CD by doing:

$ dscl . append /Groups/operator GroupMembership you

**Comment by rakslice** [comment]
Okay. 

What I had done is that I temporarily gave my user access to `/dev/disk?` by changing its permissions but not the corresponding `/dev/disk?s1`.
