### ISSUE TITLE
Support for scaling in windowed mode in SDL2

### ISSUE THREAD

**Issue by rakslice** [rakslice/macemu#22]
My main PC laptop is a 13" laptop with a 4k screen, so the DPI is well into the 200s. I'm running Gnome 3 in Debian 10's default Wayland-based setup for it.

With DPI this high, a 1:1 pixel sized window is almost too small to see for a normally-sighted person and definitely not usable.

Since SDL 1.x doesn't present any kind of obvious built-in way to do pixel scaling, for previous B2/SS versions I just scripted automatically changing the Gnome resolution & DPI settings for the duration of the B2/SS run and then changing back when done (which was quite a time consuming thing to script given how littered Gnome is with dead monitor settings interfaces).

However with SDL2, pixel scaling is essentially automatic whenever the window is a different size than the bitmap graphics output, and so setting it up is just a matter of passing a different window size -- multiplying the `window_width` and `window_height` in `video_sdl2.cpp` is a code change I can make in literally 10 seconds any time I want it -- so I haven't gotten around to seriously suggesting a change anywhere

But also I don't know what end users want for a pixel scaling feature. Some possibilities:
- Totally hands off automatic scaling determined by some thresholds on the DPI reported by SDL2 (like what I did in https://github.com/rakslice/macemu/commit/9780b7a4ceaed8b6a43e3d4808dbca24023e27ca)
- A configurable setting in the graphics prefs you can change to what you want
- 1x scale by default, but in windowed mode with SDL2, allow the window to be resized freely to scale the window content (this could be annoying without a button to set it back to the default)

**Comment by rakslice** [comment]
This is only for platforms where there isn't already a platform solutions for high DPI that works with SDL2 without the application having to do anything.

**Comment by kanjitalk755** [comment]
> A configurable setting in the graphics prefs you can change to what you want

I adopted this one (3861177).
