### ISSUE TITLE
Have Appveyor build job figure out necessary MSYS2 package DLLs for GUIs and bundle them

### ISSUE THREAD

**Issue by emendelson** [rakslice/macemu#55]
Thank you for these automatic builds. BasiliskIIGUI.exe fails with this "System Error" message:

![Capture](https://user-images.githubusercontent.com/5208505/99414200-94cb8900-28c4-11eb-899a-56053f4fb4ef.PNG)

**Comment by rakslice** [comment]
For the GUI you need the DLLs of GTK 2 and the libraries it depends on out of MSYS2's packages. I don't have a good solution for having the build figure out which ones they are automatically.

If you just want to track down a copy, the set that Cat_7 posted in the archive of with a 22-09-2020 Basilisk II build seems to be sufficient. https://www.emaculation.com/forum/viewtopic.php?p=27241#p27241

**Comment by rakslice** [comment]
But keep this open and I'll sort it out at some point.
